-- ═══════════════════════════════════════════════════════════════════════════
-- HYPRLAND MAIN CONFIGURATION (Lua)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- This is the main entry point. Configuration is split into modular files
-- for easier navigation and maintenance.
--
-- Structure:
--   config/lib.lua           - Shared values (mainMod, programs, paths)
--   config/variables.lua     - Environment variables
--   config/monitors.lua      - Monitor configurations
--   config/appearance.lua    - Colors, borders, gaps, opacity
--   config/animations.lua    - Animation curves and settings
--   config/input.lua         - Keyboard, mouse, touchpad, gestures
--   config/binds.lua         - Keybindings (grouped by function)
--   config/layouts.lua       - Dwindle/Master layout settings
--   config/autostart.lua     - Startup applications
--   config/rules.lua         - Window and workspace rules
--   config/active-shader.lua - Generated by scripts/shader-menu.sh
--
-- Paths in require() are relative to this file. Each require() is its own Lua
-- error scope, so a mistake in one module will not stop the others loading.
--
-- Edit individual files to customize your Hyprland experience.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Core Configuration ──────────────────────────────────────────────────────
require("config/variables")
require("config/monitors")
require("config/appearance")
require("config/animations")
require("config/input")
require("config/layouts")
require("config/autostart")
require("config/binds")
require("config/rules")

-- ── Runtime state ───────────────────────────────────────────────────────────
-- Written by scripts/shader-menu.sh; may not exist yet. A plain require() of a
-- missing module would kill this file, so it is wrapped in pcall().
pcall(require, "config/active-shader")
