# Wallust Zsh Template
# Automatically generated by Wallust

# Define colors for Zsh plugins
export WALLUST_BACKGROUND="#010102"
export WALLUST_FOREGROUND="#9BA2CE"
export WALLUST_ACCENT="#5F5F5C"

# Autosuggestions - use accent color instead of potentially invisible gray
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5F5F5C"

# Fix syntax highlighting visibility
# We use an init hook to ensure these are applied AFTER the plugin loads
_apply_wallust_colors() {
    # Ensure the array exists
    typeset -gA ZSH_HIGHLIGHT_STYLES

    # Commands (Valid) - We use FOREGROUND here to guarantee visibility
    # because it is always high-contrast against the background.
    ZSH_HIGHLIGHT_STYLES[command]="fg=#9BA2CE,bold"
    ZSH_HIGHLIGHT_STYLES[alias]="fg=#9BA2CE,bold"
    ZSH_HIGHLIGHT_STYLES[builtin]="fg=#9BA2CE,bold"
    ZSH_HIGHLIGHT_STYLES[function]="fg=#9BA2CE,bold"

    # Arguments and generic text
    ZSH_HIGHLIGHT_STYLES[arg0]="fg=#9BA2CE"
    ZSH_HIGHLIGHT_STYLES[default]="fg=#9BA2CE"

    # Strings and constants
    ZSH_HIGHLIGHT_STYLES[string]="fg=#8289B3"
    ZSH_HIGHLIGHT_STYLES[single-hyphen-option]="fg=#616060"
    ZSH_HIGHLIGHT_STYLES[double-hyphen-option]="fg=#616060"

    # Errors
    ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=#635245,underline"
}

# Run now
_apply_wallust_colors

# Also schedule it to run after all scripts are initialized
# This handles plugins that might reset styles during their own init
autoload -Uz add-zsh-hook
_apply_wallust_colors_hook() {
    _apply_wallust_colors
    # Remove ourselves after one run to stay clean
    add-zsh-hook -d precmd _apply_wallust_colors_hook
}
add-zsh-hook precmd _apply_wallust_colors_hook
